// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/auth/success": {
    params: {};
  };
  "/auth/error": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/orders": {
    params: {};
  };
  "/dashboard/products": {
    params: {};
  };
  "/dashboard/categories": {
    params: {};
  };
  "/dashboard/users": {
    params: {};
  };
  "/dashboard/discounts": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/order-summary": {
    params: {};
  };
  "/admin/forgot-password": {
    params: {};
  };
  "/admin/reset-password": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/email": {
    params: {};
  };
  "/profile/phone": {
    params: {};
  };
  "/profile/address": {
    params: {};
  };
  "/profile/password": {
    params: {};
  };
  "/profile/purchase": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/product/:id" | "/cart" | "/login" | "/register" | "/auth/success" | "/auth/error" | "/dashboard" | "/dashboard/orders" | "/dashboard/products" | "/dashboard/categories" | "/dashboard/users" | "/dashboard/discounts" | "/forgot-password" | "/verify-email" | "/categories" | "/search" | "/checkout" | "/admin/login" | "/order-summary" | "/admin/forgot-password" | "/admin/reset-password" | "/profile" | "/profile/email" | "/profile/phone" | "/profile/address" | "/profile/password" | "/profile/purchase";
  };
  "pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "pages/ProductDetail.tsx": {
    id: "pages/ProductDetail";
    page: "/product/:id";
  };
  "pages/cart.tsx": {
    id: "pages/cart";
    page: "/cart";
  };
  "pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  };
  "pages/Register.tsx": {
    id: "pages/Register";
    page: "/register";
  };
  "pages/AuthSuccess.tsx": {
    id: "pages/AuthSuccess";
    page: "/auth/success";
  };
  "pages/Error.tsx": {
    id: "pages/Error";
    page: "/auth/error";
  };
  "dashboard-pages/dashboard/page.tsx": {
    id: "dashboard-pages/dashboard/page";
    page: "/dashboard";
  };
  "dashboard-pages/orders/page.tsx": {
    id: "dashboard-pages/orders/page";
    page: "/dashboard/orders";
  };
  "dashboard-pages/products/page.tsx": {
    id: "dashboard-pages/products/page";
    page: "/dashboard/products";
  };
  "dashboard-pages/categories/page.tsx": {
    id: "dashboard-pages/categories/page";
    page: "/dashboard/categories";
  };
  "dashboard-pages/users/page.tsx": {
    id: "dashboard-pages/users/page";
    page: "/dashboard/users";
  };
  "dashboard-pages/discounts/page.tsx": {
    id: "dashboard-pages/discounts/page";
    page: "/dashboard/discounts";
  };
  "pages/ForgotPassword.tsx": {
    id: "pages/ForgotPassword";
    page: "/forgot-password";
  };
  "pages/VerifyEmailPage.tsx": {
    id: "pages/VerifyEmailPage";
    page: "/verify-email";
  };
  "pages/category/Category.tsx": {
    id: "pages/category/Category";
    page: "/categories";
  };
  "pages/search/Search.tsx": {
    id: "pages/search/Search";
    page: "/search";
  };
  "pages/orders/CheckoutPage.jsx": {
    id: "pages/orders/CheckoutPage";
    page: "/checkout";
  };
  "pages/admin/AdminLogin.tsx": {
    id: "pages/admin/AdminLogin";
    page: "/admin/login";
  };
  "pages/orders/OrderConfirm.jsx": {
    id: "pages/orders/OrderConfirm";
    page: "/order-summary";
  };
  "pages/admin/AdminForgot.tsx": {
    id: "pages/admin/AdminForgot";
    page: "/admin/forgot-password";
  };
  "pages/admin/AdminReset.tsx": {
    id: "pages/admin/AdminReset";
    page: "/admin/reset-password";
  };
  "pages/UserProfile.tsx": {
    id: "pages/UserProfile";
    page: "/profile" | "/profile/email" | "/profile/phone" | "/profile/address" | "/profile/password" | "/profile/purchase";
  };
  "components/profile/ProfileData.jsx": {
    id: "components/profile/ProfileData";
    page: "/profile";
  };
  "components/profile/ChangeEmail.jsx": {
    id: "components/profile/ChangeEmail";
    page: "/profile/email";
  };
  "components/profile/ChangePhone.jsx": {
    id: "components/profile/ChangePhone";
    page: "/profile/phone";
  };
  "components/profile/Address.jsx": {
    id: "components/profile/Address";
    page: "/profile/address";
  };
  "components/profile/ChangePassword.jsx": {
    id: "components/profile/ChangePassword";
    page: "/profile/password";
  };
  "components/profile/Purchase.jsx": {
    id: "components/profile/Purchase";
    page: "/profile/purchase";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/home": typeof import("./app/pages/home.tsx");
  "pages/ProductDetail": typeof import("./app/pages/ProductDetail.tsx");
  "pages/cart": typeof import("./app/pages/cart.tsx");
  "pages/Login": typeof import("./app/pages/Login.tsx");
  "pages/Register": typeof import("./app/pages/Register.tsx");
  "pages/AuthSuccess": typeof import("./app/pages/AuthSuccess.tsx");
  "pages/Error": typeof import("./app/pages/Error.tsx");
  "dashboard-pages/dashboard/page": typeof import("./app/dashboard-pages/dashboard/page.tsx");
  "dashboard-pages/orders/page": typeof import("./app/dashboard-pages/orders/page.tsx");
  "dashboard-pages/products/page": typeof import("./app/dashboard-pages/products/page.tsx");
  "dashboard-pages/categories/page": typeof import("./app/dashboard-pages/categories/page.tsx");
  "dashboard-pages/users/page": typeof import("./app/dashboard-pages/users/page.tsx");
  "dashboard-pages/discounts/page": typeof import("./app/dashboard-pages/discounts/page.tsx");
  "pages/ForgotPassword": typeof import("./app/pages/ForgotPassword.tsx");
  "pages/VerifyEmailPage": typeof import("./app/pages/VerifyEmailPage.tsx");
  "pages/category/Category": typeof import("./app/pages/category/Category.tsx");
  "pages/search/Search": typeof import("./app/pages/search/Search.tsx");
  "pages/orders/CheckoutPage": typeof import("./app/pages/orders/CheckoutPage.jsx");
  "pages/admin/AdminLogin": typeof import("./app/pages/admin/AdminLogin.tsx");
  "pages/orders/OrderConfirm": typeof import("./app/pages/orders/OrderConfirm.jsx");
  "pages/admin/AdminForgot": typeof import("./app/pages/admin/AdminForgot.tsx");
  "pages/admin/AdminReset": typeof import("./app/pages/admin/AdminReset.tsx");
  "pages/UserProfile": typeof import("./app/pages/UserProfile.tsx");
  "components/profile/ProfileData": typeof import("./app/components/profile/ProfileData.jsx");
  "components/profile/ChangeEmail": typeof import("./app/components/profile/ChangeEmail.jsx");
  "components/profile/ChangePhone": typeof import("./app/components/profile/ChangePhone.jsx");
  "components/profile/Address": typeof import("./app/components/profile/Address.jsx");
  "components/profile/ChangePassword": typeof import("./app/components/profile/ChangePassword.jsx");
  "components/profile/Purchase": typeof import("./app/components/profile/Purchase.jsx");
};